<!DOCTYPE html>
<html lang="es-LA">
<head> 
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="assets/css/global.css">
    <link rel="stylesheet" href="assets/css/style_footer.css"> 
</head>
<body>
    <!-- Formulario de inicio de sesión -->
    <form action="src/views/dashboard.php" method="post" class="login-form">
        <label for="user">Usuario</label>
        <input type="text" name="usuario" id="user" placeholder="Ingresa tu usuario" required>
        <br>
        <label for="password">Contraseña</label>
        <input type="password" name="contra" id="password" placeholder="Ingresa tu contraseña" required>
        <br>
        <button type="submit">Iniciar sesión</button>
    </form>
    <!-- Footer -->
    <?php include 'components/footer.phtml'; ?>
</body>
</html>